### ISSUE TITLE
"Exception: `internetarchive` configuration file is not configured properly."

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#111]
I succesfully configured it using ``ia configure``, so I'm not sure why its not being found. ``~/.ia`` does contain the two keys that TubeUp.py is apparently trying to find. I've updated all the pip packages to latest.

```An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tubeup/__main__.py", line 93, in main
    use_download_archive):
  File "/home/pi/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 361, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/home/pi/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 325, in upload_ia
    raise Exception(msg)
Exception: `internetarchive` configuration file is not configured properly.```

**Comment by vxbinaca** [comment]
upgrade your binaries, all of them, `internetarchive` got a massive overhaul recently.

**Comment by vxbinaca** [comment]
Delete the config files then reconfigure again.

**Comment by mariomadproductions** [comment]
Done that, still not working.
Here is the config file with sensitive bits removed:
```[s3]
access = [removed]
secret = [removed]

[cookies]
logged-in-user = [removed]%40gmail.com; expires=Wed, 31-Mar-2021 09:51:32 GMT; Max-Age=31536000; path=/; domain=.archive.org
logged-in-sig = [removed]; expires=Wed, 31-Mar-2021 09:51:32 GMT; Max-Age=31536000; path=/; domain=.archive.org

[general]
screenname = [removed]
```

**Comment by mariomadproductions** [comment]
Updated internetarchive again, as per your (deleted?) suggestion. Works now. I guess ``internetarchive`` must have broke something, then fixed it.

**Comment by vxbinaca** [comment]
Update your dependencies each time before you tun tubeup.
