### ISSUE TITLE
youtube playlists failing to upload

### ISSUE THREAD

**Issue by rjw1** [bibanon/tubeup#139]
When trying to archive a playlist I get the followign when it tries to do an upload the internet archive. The videos in the download are done fine. If I do an individual video it does upload.

Command I was running `tubeup https://www.youtube.com/playlist?list=PLuEbc43fHqLhrfE7IOt9z3bcmofPhwu7H --debug`

tubeup version
```
$  tubeup --version
0.0.20
```

youtube-dlc version
```
 $  youtube-dlc --version
2020.11.11-3
```

Error I got.

```
[DEBUG] 2020-11-21 12:03:44,706 - tubeup.TubeUp - DEBUG - Creating basenames from ydl info dict with type playlist

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tubeup/__main__.py", line 94, in main
    for identifier, meta in tu.archive_urls(URLs, metadata, proxy_url,
  File "/usr/local/lib/python3.9/site-packages/tubeup/TubeUp.py", line 366, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
  File "/usr/local/lib/python3.9/site-packages/tubeup/TubeUp.py", line 154, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/usr/local/lib/python3.9/site-packages/tubeup/TubeUp.py", line 182, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/usr/local/lib/python3.9/site-packages/youtube_dlc/YoutubeDL.py", line 660, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable
```

**Comment by vxbinaca** [comment]
this is a ytdlc problem, wait for an extractor/code update.
