### ISSUE TITLE
Tubeup uploads files even if download failed

### ISSUE THREAD

**Issue by XXLuigiMario** [bibanon/tubeup#153]
Have had the connection flake on me a couple times while downloading. Each time, tubeup uploaded partial files to archive.org instead of failing. This is especially annoying if it created ".mp4.part" files as you need to delete them manually from the item.
```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.7.3 (CPython) - Linux-4.19.75-v7+-armv7l-with-debian-10.1
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[22;0tvideo doesn't have subtitles
[debug] Default format spec: bestvideo+bestaudio/best
There are no annotations to write.
Requested formats are incompatible for merge and will be merged into mkv.
]0;youtube-dl   0.0% of 1.19GiB at 24.38KiB/s ETA 11:41
[download]  58.4% of 1.19GiB at  3.70MiB/s ETA 00:01[K[0;31mERROR:[0m unable to download video data: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/joel/.local/lib/python3.7/site-packages/youtube_dl/utils.py", line 2736, in https_open
    req, **kwargs)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

[23;0t
 uploading aIwWLCcY1bw.description:   0%|                | 0/1 [00:00<?, ?MiB/s]
 uploading aIwWLCcY1bw.description: 100%|████████| 1/1 [00:00<00:00,  1.94MiB/s]
 uploading aIwWLCcY1bw.description: 100%|████████| 1/1 [00:00<00:00,  1.93MiB/s]

 uploading aIwWLCcY1bw.info.json:   0%|                  | 0/1 [00:00<?, ?MiB/s]
 uploading aIwWLCcY1bw.info.json: 100%|██████████| 1/1 [00:00<00:00,  1.99MiB/s]
 uploading aIwWLCcY1bw.info.json: 100%|██████████| 1/1 [00:00<00:00,  1.98MiB/s]

 uploading aIwWLCcY1bw.jpg:   0%|                        | 0/1 [00:00<?, ?MiB/s]
 uploading aIwWLCcY1bw.jpg: 100%|████████████████| 1/1 [00:00<00:00,  2.00MiB/s]
 uploading aIwWLCcY1bw.jpg: 100%|████████████████| 1/1 [00:00<00:00,  1.99MiB/s]

 uploading aIwWLCcY1bw.f135.mp4.part:   0%|             | 0/10 [00:00<?, ?MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  10%|▌    | 1/10 [00:01<00:14,  1.56s/MiB]
 uploading aIwWLCcY1bw.f135.mp4.part:  20%|█    | 2/10 [00:01<00:09,  1.14s/MiB]
 uploading aIwWLCcY1bw.f135.mp4.part:  30%|█▌   | 3/10 [00:01<00:05,  1.19MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  40%|██   | 4/10 [00:01<00:03,  1.59MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  50%|██▌  | 5/10 [00:02<00:02,  2.05MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  60%|███  | 6/10 [00:02<00:01,  2.58MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  70%|███▌ | 7/10 [00:02<00:00,  3.25MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  80%|████ | 8/10 [00:02<00:00,  3.95MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part:  90%|████▌| 9/10 [00:02<00:00,  4.68MiB/s]
 uploading aIwWLCcY1bw.f135.mp4.part: 100%|████| 10/10 [00:02<00:00,  3.61MiB/s]

:: Upload Finished. Item information:
Title: Goldeneye 007 XBLA for the Xbox 360 has leaked | MVG
Upload URL: https://archive.org/details/youtube-aIwWLCcY1bw
```

**Comment by vxbinaca** [comment]
Set up a DNS caching service on your VPS.

**Comment by XXLuigiMario** [comment]
> 
> 
> Set up a DNS caching service on your VPS.
> 
> Upgrade your youtube-dl and internetarchive as well.

This is not a DNS issue. The download had already begun and later the socket timed out.
tubeup should be able to catch errors from youtube-dl and not proceed to upload in that case.

**Comment by vxbinaca** [comment]
It can if you code it, or IA could disallow uploads of .temp, .ytdl and .part files.

**Comment by vxbinaca** [comment]
Consider deleting the contents of that item and re-rip.

**Comment by brandongalbraith** [comment]
Notes to self for cutting PR:

[ ] Internet Archive will prevent the upload of `.part` files. This is good! But we should not even attempt to upload them. Filter locally when iterating over objects to be uploaded.
[ ] Improve youtube-dl failure detection to ensure we're not left in a poor state between retrieval and upload.

**Comment by brandongalbraith** [comment]
@vxbinaca Are uploads successful with the new version you cut? If so, this can be closed.

**Comment by vxbinaca** [comment]
> @vxbinaca Are uploads successful with the new version you cut? If so, this can be closed.

He wrote to the item I can't test that exact extractor. Your code disallowing .part uploads passes unit tests so AFAIC it's kosher.

He's need to produce another failure with `0.0.27`.
