### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by RandomBlbosti** [bibanon/tubeup#159]
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Roaming\Python\Python38\site-packages\tubeup\__main__.py", line 94, in main
    for identifier, meta in tu.archive_urls(URLs, metadata, proxy_url,
  File "C:\Users\Acer\AppData\Roaming\Python\Python38\site-packages\tubeup\TubeUp.py", line 371, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "C:\Users\Acer\AppData\Roaming\Python\Python38\site-packages\tubeup\TubeUp.py", line 285, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Acer\\.tubeup\\downloads\\UCNW2BjRAba8yM_rQtwnAnpQ.info.json' (I have tried making the file and making it blank, but that doesn't work)

**Comment by vxbinaca** [comment]
No URL we can test against
