### ISSUE TITLE
Error caused by latest internetarchive update

### ISSUE THREAD

**Issue by Moocow93** [bibanon/tubeup#171]
Whenever I try to archive a video I get this error
`An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tubeup/__main__.py", line 99, in main
    use_download_archive):
  File "/usr/local/lib/python3.7/dist-packages/tubeup/TubeUp.py", line 381, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.7/dist-packages/tubeup/TubeUp.py", line 332, in upload_ia
    parsed_ia_s3_config = parse_config_file(self.ia_config_path)[1]['s3']
TypeError: 'bool' object is not subscriptable`
This only seems to happen with the module internetarchive 2.1.0 released recently, going back to 2.0.3 fixes this error.

**Comment by vxbinaca** [comment]
You failed to read the submission guidelines.

**Comment by vxbinaca** [comment]
@brandongalbraith
