### ISSUE TITLE
Bug report: Failed uploading

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#223]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [X ] I have fully updated tubeup, youtube-dl and internetarchive along with their associated dependencies.
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the issues (closed or open) for similar bug reports including closed ones
- [ X] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [ X] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [X ] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

`ia --version`

**Expected behavior**

**Additional context**

`tubeup --use-download-archive --ignore-existing-item --metadata=collection:weedtubers https://www.youtube.com/watch?v=2Qhh_0L2orY`

```
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/vxbinaca/myenvdir/lib/python3.9/site-packages/tubeup/__main__.py", line 103, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/vxbinaca/myenvdir/lib/python3.9/site-packages/tubeup/TubeUp.py", line 415, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
  File "/home/vxbinaca/myenvdir/lib/python3.9/site-packages/tubeup/TubeUp.py", line 189, in get_resource_basenames
    downloaded_files_basename.update(self.create_basenames_from_ydl_info_dict(ydl, info_dict))
  File "/home/vxbinaca/myenvdir/lib/python3.9/site-packages/tubeup/TubeUp.py", line 207, in create_basenames_from_ydl_info_dict
    info_type = info_dict.get('_type', 'video')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by vxbinaca** [comment]
Removed `--use-download-archive` fixed it whoops, but still why did these fail in the first place?
