### ISSUE TITLE
Null date metadata causing uploads to fail

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#25]
```tubeup https://www.facebook.com/327319634141163/videos/362921167247676/```

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.22
[debug] Python version 3.5.2 - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: [redacted]
{'_total_bytes_str': '4.45MiB', '_elapsed_str': '00:09', 'total_bytes': 4666441, 'status': 'finished', 'filename': '/home/vxbinaca/.tubeup/downloads/Facebook_video_362921167247676-362921167247676.mp4', 'elapsed': 9.106133937835693, 'downloaded_bytes': 4666441}
:: Downloaded: /home/vxbinaca/.tubeup/downloads/Facebook_video_362921167247676-362921167247676.mp4...
:: Uploading /home/vxbinaca/.tubeup/downloads/Facebook_video_362921167247676-362921167247676...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 252, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 141, in upload_ia
    d = datetime.strptime(vid_meta['upload_date'], '%Y%m%d')
KeyError: 'upload_date'
```

This is on our end because it completes the download. However Facebook + youtube-dl is a little funky sometimes......a lot of the time but this is the first failure I've had to even upload. Most other problems are just metadata ending up in the title of the item.

Edit: The metadata;

```
{"uploader": null, "extractor": "facebook", "display_id": "362921167247676", "format": "progressive_hd_src_no_ratelimit - unknown", "webpage_url_basename": "362921167247676", "format_id": "progressive_hd_src_no_ratelimit", "extractor_key": "Facebook", "playlist": null, "webpage_url": "https://www.facebook.com/327319634141163/videos/362921167247676/", "fulltitle": "Facebook video #362921167247676", "http_headers": {"Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, "formats": [{"format_id": "progressive_sd_src", "ext": "mp4", "http_headers": {"Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, "preference": -10, "protocol": "https", "format": "progressive_sd_src - unknown", "url": "https://video-mia1-1.xx.fbcdn.net/v/t42.1790-2/11194096_362921810580945_1666410974_n.mp4?efg=eyJybHIiOjM0NSwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoicmVzXzQyNl9jcmZfMjNfbWFpbl8zLjBfc2QifQ%3D%3D&rl=345&vabr=192&oh=a63103da7c38aa5aa862dbc17406cda4&oe=5793473A"}, {"format_id": "progressive_sd_src_no_ratelimit", "ext": "mp4", "http_headers": {"Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, "preference": -10, "protocol": "https", "format": "progressive_sd_src_no_ratelimit - unknown", "url": "https://video-mia1-1.xx.fbcdn.net/v/t42.1790-2/11194096_362921810580945_1666410974_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InJlc180MjZfY3JmXzIzX21haW5fMy4wX3NkIn0%3D&oh=a63103da7c38aa5aa862dbc17406cda4&oe=5793473A"}, {"format_id": "progressive_hd_src", "ext": "mp4", "http_headers": {"Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, "preference": -5, "protocol": "https", "format": "progressive_hd_src - unknown", "url": "https://video-mia1-1.xx.fbcdn.net/v/t43.1792-2/11067207_362921663914293_663837328_n.mp4?efg=eyJybHIiOjE1MDAsInJsYSI6MTAyNCwidmVuY29kZV90YWciOiJoZCJ9&rl=1500&vabr=760&oh=0b6d008a52ec9d8a699093a6e41b1528&oe=579345C3"}, {"format_id": "progressive_hd_src_no_ratelimit", "ext": "mp4", "http_headers": {"Accept-Language": "en-us,en;q=0.5", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Encoding": "gzip, deflate", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, "preference": -5, "protocol": "https", "format": "progressive_hd_src_no_ratelimit - unknown", "url": "https://video-mia1-1.xx.fbcdn.net/v/t43.1792-2/11067207_362921663914293_663837328_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImhkIn0%3D&oh=0b6d008a52ec9d8a699093a6e41b1528&oe=579345C3"}], "_filename": "/home/vxbinaca/.tubeup/downloads/Facebook_video_362921167247676-362921167247676.mp4", "preference": -5, "protocol": "https", "title": "Facebook video #362921167247676", "url": "https://video-mia1-1.xx.fbcdn.net/v/t43.1792-2/11067207_362921663914293_663837328_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImhkIn0%3D&oh=0b6d008a52ec9d8a699093a6e41b1528&oe=579345C3", "ext": "mp4", "playlist_index": null, "id": "362921167247676"}
```

**Comment by vxbinaca** [comment]
```
tubeup --metadata=collection:opensource_audio http://www.bbc.co.uk/programmes/p041mfht
```

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.22
[debug] Python version 3.5.2 - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[debug] Public IP address: 73.156.11.171
{'elapsed': 122.3196325302124, 'filename': '/home/vxbinaca/.tubeup/downloads/The_live_streaming_Arab_Spring_BBC_Trending_-_BBC_World_Service-p041mfw2.mp4', '_elapsed_str': '02:02', 'downloaded_bytes': 8285160, '_total_bytes_str': '7.90MiB', 'status': 'finished', 'total_bytes': 8285160}
:: Downloaded: /home/vxbinaca/.tubeup/downloads/The_live_streaming_Arab_Spring_BBC_Trending_-_BBC_World_Service-p041mfw2.mp4...
:: Uploading /home/vxbinaca/.tubeup/downloads/The_live_streaming_Arab_Spring_BBC_Trending_-_BBC_World_Service-p041mfw2...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 252, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 141, in upload_ia
    d = datetime.strptime(vid_meta['upload_date'], '%Y%m%d')
KeyError: 'upload_date'
```

**Comment by jjjake** [comment]
I'll take a look at this @vxbinaca.

**Comment by vxbinaca** [comment]
@jjjake Take your time I'll be out of town for the next week at ALOA (Locksmith conference). I'll periodically check in.

**Comment by vxbinaca** [comment]
I decided to instead submit a bug report to youtube-dl since I found that upload date was missing from the metadata. Will close if this fixes it.

**Comment by jjjake** [comment]
@vxbinaca let me know if it doesn't. This would be an easy fix on the tubeup end of things, but it would definitely be better to fix it upstream so we can get dates if they're available!

**Comment by vxbinaca** [comment]
@jjjake I'm waiting for this months first youtube-dl to release. In the meantime I'm trying to account for a much more perplexing and damaging upstream problem. [See my comment.] (https://github.com/rg3/youtube-dl/commit/92c27a0dbf19eff211e7ffdd8db5895387e75529)

**Comment by vxbinaca** [comment]
Closing because when I find a site without metadata, 99 percent of the time we'll be able to escape it by getting youtube-dl to pull the date or whatever needed. However I agree the script should have a fail-safe built in that just scraps the lack of date and uploads anyway when it doesn't encounter one. Babysitting uploads will minimize this bugs impact.
