### ISSUE TITLE
tubeup completely fails to grab video

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#28]
```tubeup https://www.youtube.com/watch?v=Yeb08cbUswk```

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.5.2 - Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 697, in create_connection
    sock = socket(af, socktype, proto)
  File "/usr/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 241, in main
    download(URLs, proxy_url)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 110, in download
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 367, in __init__
    self.print_debug_header()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2055, in print_debug_header
    ipaddr = self.urlopen('https://yt-dl.org/ip').read().decode('utf-8')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1996, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 1004, in https_open
    req, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 97] Address family not supported by protocol>
```

Youtube-dl gets the video, but tubeup doesn't. Need me to print out the dependency versions?

dependency versions:

youtube-dl: 2016.8.22
requests: 2.11.1
jsonpatch: 0.4
internetarchive: 1.0.9
tubeup: Version: 0.0.1

So this looks like a problem with ```requests```, is this related to the problem you had with internetarchive? I'll take a look at how it was fixed and try to replicate.

**Comment by vxbinaca** [comment]
Re-installing everything fixed this
