### ISSUE TITLE
Bug report: Video impossible to upload when best quality stream is unavailable on the server-side

### ISSUE THREAD

**Issue by XXLuigiMario** [bibanon/tubeup#308]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [x] I have fully updated `tubeup`, `yt-dlp` and `internetarchive` along with their associated dependencies.
- [x] I've included the full and unredacted URL and console output (with the exception of site usernames and passwords, or IP addresses of the machine doing the download). Hiding URLs will get issue closed.
- [x] I've checked that all provided URLs are alive, playable in a browser and arguments with special characters are properly quoted or escaped.
- [x] I've searched the issues (closed or open) for similar bug reports including closed ones
- [x] I'm not submitting a bug report about IA S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [x] I'm not submitting a bug report about NSIG timeouts (this is beyond tubeups control and is a yt-dlp issue)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).
- [x] I am putting all of the required information in the original issue post and not adding it to a following comment.

**Dependency versions**

Please provide version information from core dependencies:

`ia --version` 3.5.0
`yt-dlp --version` 2023.07.06

**Expected behavior**
The video is downloaded in the best possible quality and uploaded to the Internet Archive.

**Problem**
The command "tubeup https://youtu.be/Pj_ED7YrvDc" gets stuck at 98.2%

```
Rudy Rants - 9 BILLION POKEMON CARDS
There are no annotations to write.
[download]  98.2% of  278.88MiB at  983.49KiB/s ETA 00:05
```

Attempting the same download with the best possible settings using `yt-dlp` fails exactly the same:
```

[youtube] Extracting URL: https://youtu.be/Pj_ED7YrvDc
[youtube] Pj_ED7YrvDc: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] Pj_ED7YrvDc: Downloading ios player API JSON
[youtube] Pj_ED7YrvDc: Downloading android player API JSON
[youtube] Pj_ED7YrvDc: Downloading iframe API JS
[youtube] Pj_ED7YrvDc: Downloading player 21812a9c
[youtube] Pj_ED7YrvDc: Downloading web player API JSON
[youtube] Pj_ED7YrvDc: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] Pj_ED7YrvDc: Downloading initial data API JSON
[info] Pj_ED7YrvDc: Downloading 1 format(s): 303+251
[download] Destination: Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].f303.webm
[download]  98.2% of  278.88MiB at  173.21KiB/s ETA 00:28[download] Got error: HTTP Error 503: Service Unavailable. Retrying (1/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (2/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (3/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (4/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (5/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (6/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (7/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (8/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (9/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (10/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Giving up after 10 retries

[download] Destination: Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].f251.webm
[download] 100% of   10.10MiB in 00:00:00 at 25.59MiB/s
```

At first glance, the video is fully playable on YouTube, at 1080p 60 fps. However, if we check the codec settings, we'll see it's actually using a different format, 399 (the preferred AV1 stream) instead of 303 (the preferred VP9 stream), which is determined to be the best quality video by yt-dlp. If we force the youtube video to play the 303 codec, it hangs at about 10:25:

![imatge](https://github.com/bibanon/tubeup/assets/7153662/b6378041-fde7-4e11-b022-6dc8e421e631)

I did this by disabling AV1 codec with the [enhanced-h264ify](https://addons.mozilla.org/en-US/firefox/addon/enhanced-h264ify/) Firefox extension:
![imatge](https://github.com/bibanon/tubeup/assets/7153662/efac4d49-cffc-483f-b114-28cbb5f564fe)

Clearly something is wrong with the 303 stream for this video. We opt to download the preferred AV1 stream instead with yt-dlp:

yt-dlp -f '399+251' https://youtu.be/Pj_ED7YrvDc

This time it succeeds:
```
[youtube] Extracting URL: https://youtu.be/Pj_ED7YrvDc
[youtube] Pj_ED7YrvDc: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] Pj_ED7YrvDc: Downloading ios player API JSON
[youtube] Pj_ED7YrvDc: Downloading android player API JSON
[youtube] Pj_ED7YrvDc: Downloading iframe API JS
[youtube] Pj_ED7YrvDc: Downloading player 21812a9c
[youtube] Pj_ED7YrvDc: Downloading web player API JSON
[youtube] Pj_ED7YrvDc: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] Pj_ED7YrvDc: Downloading initial data API JSON
[info] Pj_ED7YrvDc: Downloading 1 format(s): 399+251
[download] Destination: Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].f399.mp4
[download] 100% of  203.11MiB in 00:00:06 at 33.72MiB/s
[download] Destination: Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].f251.webm
[download] 100% of   10.10MiB in 00:00:00 at 22.83MiB/s
[Merger] Merging formats into "Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].webm"
Deleting original file Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].f399.mp4 (pass -k to keep)
Deleting original file Rudy Rants - 9 BILLION POKEMON CARDS [Pj_ED7YrvDc].f251.webm (pass -k to keep)
```

Unfortunately, tubeup does not allow overriding yt-dlp's choice of format. This seems like a sane choice considering we always want to upload the best quality video to the Internet Archive for archival purposes. That said, what should we do if the best quality stream is unretrievable? Perhaps there should be a way to upload the next best quality stream (which would still be 1080p60 in this case).

**Comment by vxbinaca** [comment]
Oh it's a bug alright, just not ours. Tubeup doesn't download video. yt-dlp does. Report to them.

**Comment by vxbinaca** [comment]
Is your `ffmpeg` up to date?

![image](https://github.com/bibanon/tubeup/assets/12656590/10442f86-a920-49cb-ba07-6cb772c19290)

[My test uploaded first try](https://archive.org/details/youtube-Pj_ED7YrvDc)

>Unfortunately, tubeup does not allow overriding yt-dlp's choice of format

Fortunately best quality is forced. If the result can't mux, webm is chosen by yt-dlp. Webm is streamable amd able to handle mux of anything thrown at it. 

What platform are you using?

**Comment by vxbinaca** [comment]
![image](https://github.com/bibanon/tubeup/assets/12656590/930229e2-c933-4966-b57b-56fc31ec3614)

**Comment by XXLuigiMario** [comment]
That's certainly strange. Stream 303 is a no go for me, yet it did download fine for you.
I'm testing from both my VPS and personal computer. ffmpeg versions are `ffmpeg version 4.1.6-1~deb10u1+rpt1` and `ffmpeg version 4.3.6-0+deb11u1` respectively. However, it hangs on my browser too so it's strange.

Very odd, but at least I'm glad you got it. I did find a related issue https://github.com/ytdl-org/youtube-dl/issues/25551, and similarly I can play that stream just fine. So perhaps it's just corrupted on some cache edge server?

Maybe the best thing is to let it rest for a bit in these cases. I'll be closing this, then.

**Comment by vxbinaca** [comment]
>So perhaps it's just corrupted on some cache edge server?

Perhaps. Could be on your end. Do you use a ISP-external DNS? Like 8.8.8.8 or 1.1.1.1?

Also try cleaning yt-dlps cache. Even rebooting, or just waiting.

**Comment by XXLuigiMario** [comment]
I'm used to running `rm -r .tubeup/ .cache/` between failed tries. I also tell tubeup to use a proxy for my uploads both to shield my home IP from being rate limited by YouTube or leaked by yt-dlp in the json files. I'm at a bit of a loss here.

Guess it's best to wait or switch to a proxy in a different geographic location. Thanks for your time.

**Comment by XXLuigiMario** [comment]
@vxbinaca I seem to have run into a new case, and I believe you'll be able to reproduce this one. This one does not appear that this one can be fixed simply by waiting and it freezes before it even begins downloading.

The command "tubeup https://youtu.be/WdGPmIkrfUM" produces this, then hangs:
```
LiL GUiU i MARE THE OWNER - SiNDROME DE UPP / PROD PAR TRAMPA$ KiD / AL.LUSiNANN
There are no annotations to write.
```

If you wait long enough (a long time), it will spit this out:
```
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 9001 retries
  File "/home/joel/.local/bin/tubeup", line 8, in <module>
    sys.exit(main())
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/__main__.py", line 103, in main
    ignore_existing_item):
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 419, in archive_urls
    ignore_existing_item)
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 188, in get_resource_basenames
    ydl_progress_each(info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 128, in ydl_progress_each
    ydl.extract_info(entry['webpage_url'])
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1564, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1731, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1790, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2929, in process_video_result
    self.process_info(new_info)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3377, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3116, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 385, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 524, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 473, in download_fragment
    ctx, fragment['url'], info_dict, headers, info_dict.get('request_data')):
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 124, in _download_fragment
    success, _ = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/http.py", line 362, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/utils/_utils.py", line 5092, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/common.py", line 406, in report_retry
    suffix=f'fragment{"s" if frag_index is None else f" {frag_index}"}' if is_frag else None)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/utils/_utils.py", line 5099, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/common.py", line 404, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1053, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: fragment 1 not found, unable to continue
  File "/home/joel/.local/bin/tubeup", line 8, in <module>
    sys.exit(main())
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/__main__.py", line 103, in main
    ignore_existing_item):
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 419, in archive_urls
    ignore_existing_item)
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 188, in get_resource_basenames
    ydl_progress_each(info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 128, in ydl_progress_each
    ydl.extract_info(entry['webpage_url'])
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1564, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1731, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1790, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2929, in process_video_result
    self.process_info(new_info)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3377, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3116, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 385, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 526, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/downloader/fragment.py", line 489, in append_fragment
    self.report_error(f'fragment {frag_index} not found, unable to continue')
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1053, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/joel/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

[download] 100.0% of    4.07MiB at    5.62MiB/s ETA 00:00
Downloaded /mnt/stuff/.tubeup/downloads/WdGPmIkrfUM.f251.webm

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/__main__.py", line 103, in main
    ignore_existing_item):
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 421, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/home/joel/.local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 335, in upload_ia
    raise Exception(msg)
Exception: Video download incomplete, please re-run or delete video stubs in downloads folder, exiting...

ERROR: [Errno 32] Broken pipe
```

Again, using `yt-dlp` also fails, much quicker:
```
[youtube] Extracting URL: https://youtu.be/WdGPmIkrfUM
[youtube] WdGPmIkrfUM: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] WdGPmIkrfUM: Downloading ios player API JSON
[youtube] WdGPmIkrfUM: Downloading android player API JSON
[youtube] WdGPmIkrfUM: Downloading iframe API JS
[youtube] WdGPmIkrfUM: Downloading player 16f9263d
[youtube] WdGPmIkrfUM: Downloading web player API JSON
[youtube] WdGPmIkrfUM: Downloading m3u8 information
[youtube] WdGPmIkrfUM: Downloading MPD manifest
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] WdGPmIkrfUM: Downloading initial data API JSON
[info] WdGPmIkrfUM: Downloading 1 format(s): 244+251
[dashsegments] Total fragments: 53
[download] Destination: LiL GUiU i MARE THE OWNER - SiNDROME DE UPP ⧸ PROD PAR TRAMPA$ KiD ⧸ AL.LUSiNANN [WdGPmIkrfUM].f244.webm
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (1/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (2/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (3/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (4/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (5/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (6/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (7/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (8/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (9/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (10/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

[download] Destination: LiL GUiU i MARE THE OWNER - SiNDROME DE UPP ⧸ PROD PAR TRAMPA$ KiD ⧸ AL.LUSiNANN [WdGPmIkrfUM].f251.webm
[download] 100% of    4.07MiB in 00:00:00 at 17.14MiB/s
```

I've done some digging, and this appears to be an instance of https://github.com/yt-dlp/yt-dlp/issues/502
YouTube will sometimes report video formats which somehow don't exist. If these end up being the preferred format, it renders the video unable to be uploaded by tubeup.

I also found [this particular comment](https://github.com/yt-dlp/yt-dlp/issues/502#issuecomment-928925464) interesting:
> fragments failing throughout the download - these seem to be resolved fine by the retry mechanism. Re-downloading the file again, there was no failing fragments and video download was faster. I'm guessing this is probably due to server side cache, failed fragments prob due to downloading faster than backend could keep up. Nothing abnormal here afaik.

A different, but similar case which sounds oddly familiar to what I ran into with the other video...

In any case, the suggested fix is to include the `--check-formats` flag, which will attempt to filter formats that are not actually available. However, I couldn't get this to work myself so I suppose I'll open an issue on the yt-dlp repository.
Even if it did work, I'm not sure if it would be suitable to use in our case as it appears to crudely attempt to download formats in order by preference, meaning that transient connection issues could cause a worse format to be chosen?
That said, I can't seem to think of a better fix either. It seems YouTube can't stop messing shit up these days.

**Comment by vxbinaca** [comment]
You've found not one but two site problems that are not only not ours but not yt-dlps probably either, unless they want to update the extractor.

If you're patient, yt-dlp will be updated to possibly fix this. This isn't an us thing. No we're not turning off best+best. No we're not letting users turn it off either. If you cam come up with a fix that does not involve quality degredation it will be considered.

That video is insane lol.

**Comment by vxbinaca** [comment]
>unable to extract initial player response

Extractor problem. Wait for yt-dlp to fix.

**Comment by vxbinaca** [comment]
@XXLuigiMario https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2023.08.31.204930

**Comment by vxbinaca** [comment]
I forgot to close this, feel free to force open again if the nightly or coming stable build doesn't fix your woes on this issue.
