### ISSUE TITLE
Bug report: Exception when running tubeup

### ISSUE THREAD

**Issue by elgato9857** [bibanon/tubeup#327]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [X ] I understand Tubeup is merely a middleman between `yt-dlp` and `internetarchive`, and relies on said package dependiencies functioning properly, for example: Site extractors in `yt-dlp` become stale or sites change layout breaking regex, and `internetarchive` has outages or throttles users S-3 access, and that these things are beyond the control of the maintainers of Tubeup.
- [ X] I've updated `tubeup`, `yt-dlp` and `internetarchive` along with their associated dependencies to their latest versions as supported by each afformentioned package setup scripts.
- [ X] I've included the full and unredacted URL and console output (with the exception of site usernames and passwords, or IP addresses of the machine doing the download). I understand hiding URLs will get issue closed on sight.
- [X ] I've checked that all provided URLs are alive, playable in a browser and arguments with special characters are properly quoted or escaped.
- [X ] I've searched the issues (closed or open) for similar bug reports, not just here on Tubeup, but [yt-dlps issue tracker](https://github.com/yt-dlp/yt-dlp/issues) for download issues similar to mine and [internetarchives issue tracker](https://github.com/jjjake/internetarchive/issues) for upload issues similar to mine. YT-DLP has an issue up [listing known bugs](https://github.com/yt-dlp/yt-dlp/issues/3766).
- [ X] I'm not submitting a bug report about IA S3 timeouts (we have no control over Internet Archive outages or per-user throttling, and sometimes the site has maintence like hard disk swaps)
- [X ] I've checked the [X account for Internet Archive](https://x.com/internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [ X] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

yt-dlp version: 2024.04.09

`yt-dlp --version`

`internetarchive` python client version: 3.5.0
`ia --version`

Tubeup version:2023.08.19

`tubeup --version`

**Expected behavior**
Download of the video, upload to IA.

**Additional context**
Error received-
ERROR: [youtube] Sgg7FMH4fqo: The following content is not available on this app.. Watch on the latest version of YouTube.
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 99, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 411, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 183, in get_resource_basenames
    if info_dict.get('_type', 'video') == 'playlist':
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

^C^CTraceback (most recent call last):
  File "/home/administrator/.local/bin/tubeup", line 5, in <module>
    from tubeup.__main__ import main
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 59, in <module>
    import internetarchive
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/internetarchive/__init__.py", line 42, in <module>
    from internetarchive.api import (
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/internetarchive/api.py", line 33, in <module>
    import requests
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/urllib3/__init__.py", line 18, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/urllib3/connectionpool.py", line 5, in <module>
    import queue
  File "/usr/lib/python3.12/queue.py", line 9, in <module>
    from _queue import SimpleQueue
KeyboardInterrupt
administrator@tubeup1:~/.tubeup/downloads$ yt-dlp --version
2024.04.09
administrator@tubeup1:~/.tubeup/downloads$ ia --version
3.5.0
administrator@tubeup1:~/.tubeup/downloads$ tubeup --version
2023.08.19
administrator@tubeup1:~/.tubeup/downloads$ ./download.sh
ERROR: [youtube] Sgg7FMH4fqo: The following content is not available on this app.. Watch on the latest version of YouTube.
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 99, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 411, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 183, in get_resource_basenames
    if info_dict.get('_type', 'video') == 'playlist':
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

^C^CERROR: [youtube] 3Xwx-1FY7ck: The following content is not available on this app.. Watch on the latest version of YouTube.
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 99, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 411, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 183, in get_resource_basenames
    if info_dict.get('_type', 'video') == 'playlist':
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

ERROR: [youtube] cM1l07Pcdnk: The following content is not available on this app.. Watch on the latest version of YouTube.
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 99, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 411, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/TubeUp.py", line 183, in get_resource_basenames
    if info_dict.get('_type', 'video') == 'playlist':
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

^C^CTraceback (most recent call last):
  File "/home/administrator/.local/bin/tubeup", line 5, in <module>
    from tubeup.__main__ import main
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 59, in <module>
    import internetarchive
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/internetarchive/__init__.py", line 42, in <module>
    from internetarchive.api import (
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/internetarchive/api.py", line 33, in <module>
    import requests
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/urllib3/__init__.py", line 14, in <module>
    from . import exceptions
  File "/home/administrator/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/urllib3/exceptions.py", line 7, in <module>
    from http.client import IncompleteRead as httplib_IncompleteRead
  File "/usr/lib/python3.12/http/client.py", line 1448, in <module>
    import ssl
  File "/usr/lib/python3.12/ssl.py", line 944, in <module>
    class SSLSocket(socket):
  File "/usr/lib/python3.12/ssl.py", line 1062, in SSLSocket
    @_sslcopydoc
     ^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 938, in _sslcopydoc
    def _sslcopydoc(func):

KeyboardInterrupt

**Comment by mrpapersonic** [comment]
> ERROR: [youtube] Sgg7FMH4fqo: The following content is not available on this app.. Watch on the latest version of YouTube.

yt-dlp issue. not our problem

**Comment by elgato9857** [comment]
> He didn't indent also his yt-dlp version is stale.

I’m not sure what you mean by indent. I figured that the version was stale, however, when I run the following command that no packages are updated.

   pipx upgrade-all

**Comment by elgato9857** [comment]
Here's what I get:
```
yt-dlp --update-to nightly
Current version: stable@2024.04.09 from yt-dlp/yt-dlp
Latest version: nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds
ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.

```
Pip is not installed:
```
administrator@tubeup1:~/.tubeup/downloads$ pip uninstall tubeup
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
```

**Comment by mrpapersonic** [comment]
> ```
> ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.
> ```

Don't install yt-dlp through your system's package manager (apt-get in this case), install pip and then get the latest release of yt-dlp. Debian and its derivatives typically will have very old packages.

**Comment by elgato9857** [comment]
Ok, here's the result:
```
administrator@tubeup1:~/.tubeup/downloads$ pipx uninstall yt-dlp
Nothing to uninstall for yt-dlp 😴
```

Went ahead and uninstalled with apt also:
```
administrator@tubeup1:~/.tubeup/downloads$ sudo apt-get remove yt-dlp
[sudo] password for administrator:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-mutagen python3-pycryptodome python3-websockets
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  yt-dlp
0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
After this operation, 10.5 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 138345 files and directories currently installed.)
Removing yt-dlp (2024.04.09-1) ...
Processing triggers for man-db (2.12.0-4build2) ...
```

This worked:
```
administrator@tubeup1:~/.tubeup/downloads$ pipx inject tubeup "yt-dlp[default] @ https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.06.27.232805/yt-dlp.tar.gz"
  injected package yt-dlp into venv tubeup
done! ✨ 🌟 ✨
```

As of now, it seems to be fixed!
