### ISSUE TITLE
504 Server Error when uploading yt playlist

### ISSUE THREAD

**Issue by rudolphos** [bibanon/tubeup#38]
I uploaded a playlist from youtube, this is the error I got and archiving stopped, similar error I posted some months ago, but it still happens.
```
:: Uploading ../home/.tubeup/downloads/The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM...
2017-06-27 20:24:35,188 - internetarchive.item - INFO - uploaded The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.jpg to https://s3.us.archive.org/youtube-V11Bq1ZdSqM/The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.jpg
2017-06-27 20:24:35,189 - internetarchive.item - INFO - The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.jpg successfully uploaded to https://archive.org/download/youtube-V11Bq1ZdSqM/The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.jpg and verified, deleting local copy
2017-06-27 22:24:37,074 - internetarchive.item - ERROR -  error uploading The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.description to youtube-V11Bq1ZdSqM,
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 645, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://s3.us.archive.org/youtube-V11Bq1ZdSqM/The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.description

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 208, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 771, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 665, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading The_Unreported_Facts_About_Libya_True_News-V11Bq1ZdSqM.description to youtube-V11Bq1ZdSqM
```

**Comment by vxbinaca** [comment]
Funny I was just about to make a bug report for `internetarchive` because there's a problem with it.

What version of `internetarchive` are you using? (to find out run `ia --version`)

**Comment by rudolphos** [comment]
@vxbinaca 

```
ia --version
1.5.0
```

**Comment by vxbinaca** [comment]
Don't upgrade `internetarchive` yet then.

Your problem appears to be unrealted. Perhaps try again after removing that specific videos entry (and everything below it) from your `~/.tubeup/.ytdlarchive'  file? Also don't forget to clear out your downloads folder by running `rm ~/.tubeup/downloads/*'.

**Comment by vxbinaca** [comment]
If you're running this on a machine you have sudo access to, do this:

`sudo pip3 install - U tubeup`

I'd you're just using someone else's box:

`pip3 install --user - U tubeup`

This should fix the problem there was conflicting values for `timeout` that were just baked into `Internetarchive` and Tubeup was calling a different value and it caused uploads to stop due to ia panicking. 

Report back if it works or not.

**Comment by rudolphos** [comment]
@vxbinaca 

```
Installing collected packages: backports.csv, internetarchive
  Found existing installation: internetarchive 1.5.0
    Uninstalling internetarchive-1.5.0:
      Successfully uninstalled internetarchive-1.5.0
Successfully installed backports.csv-1.0.5 internetarchive-1.6.0
```

I updated ia. I'll see how it goes, because this error didn't show up always and when running the same link it finished the playlist but I guess that video which showed 504 didn't upload.

**Comment by vxbinaca** [comment]
504 is a gateway timeout, something we don't have control over if I recall correctly. 

I'm leaving this open until @jjjake updates the pip copy of internetarchive. Once that happens I'll tag you .and then close the issue/.

**Comment by vxbinaca** [comment]
This issue was resolved months ago. Closing.

Also @rudolphos you're lucky because you have most/all of Chris Cantwells works before Google purged them. Nice going on that rip.
