### ISSUE TITLE
Twitter Video Upload Doesn't Work

### ISSUE THREAD

**Issue by dkl3** [bibanon/tubeup#47]
The output is long but is listed below:

```
~$ tubeup  https://twitter.com/GreenDay/status/910545872206700544 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.5.2 - Linux-4.10.0-35-generic-i686-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[debug] Public IP address: 2601:600:9880:390:818a:d092:d4b2:18e
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/0/3000/720x720/JlgHY8tqYPhoFq5U.ts', offset 0, playlist 0
Input #0, hls,applehttp, from 'https://video.twimg.com/amplify_video/910541641295024128/pl/720x720/t47yOs5lhHTKUeBh.m3u8':
  Duration: 00:00:47.80, start: 0.083411, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 4 reference frames ([27][0][0][0] / 0x001B), yuv420p, 720x720, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 131 kb/s
[mp4 @ 0x89c8880] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x89c8880] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:/home/USER/.tubeup/downloads/Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.mp4.part':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264, 1 reference frame ([33][0][0][0] / 0x0021), yuv420p, 720x720 (0x0), q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 131 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/3000/6000/720x720/qIFQaitii_YHqMod.ts', offset 0, playlist 0
frame=   72 fps=0.0 q=-1.0 size=      88kB time=00:00:03.00 bitrate= 239.0kbits/[mp4 @ 0x89c8880] Non-monotonous DTS in output stream 0:0; previous: 259008, current: 255255; changing to 259009. This may result in incorrect timestamps in the output file.
[mp4 @ 0x89c8880] Non-monotonous DTS in output stream 0:0; previous: 259009, current: 259009; changing to 259010. This may result in incorrect timestamps in the output file.
[mp4 @ 0x89c8880] Non-monotonous DTS in output stream 0:1; previous: 143360, current: 140380; changing to 143361. This may result in incorrect timestamps in the output file.
[mp4 @ 0x89c8880] Non-monotonous DTS in output stream 0:1; previous: 143361, current: 141404; changing to 143362. This may result in incorrect timestamps in the output file.
[mp4 @ 0x89c8880] Non-monotonous DTS in output stream 0:1; previous: 143362, current: 142428; changing to 143363. This may result in incorrect timestamps in the output file.
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/6000/9000/720x720/wymTxyER4S2KE4TG.ts', offset 0, playlist 0
frame=  144 fps=127 q=-1.0 size=     193kB time=00:00:05.93 bitrate= 266.2kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/9000/12000/720x720/Suktx8aayROR8tsH.ts', offset 0, playlist 0
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/12000/15000/720x720/yJjTN5JIiu8OIjkc.ts', offset 0, playlist 0
frame=  288 fps=170 q=-1.0 size=     427kB time=00:00:11.92 bitrate= 293.0kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/15000/18000/720x720/vmWDw9xnXVE0R1ac.ts', offset 0, playlist 0
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/18000/21000/720x720/FgWNli2K3FOftEaS.ts', offset 0, playlist 0
frame=  432 fps=191 q=-1.0 size=     644kB time=00:00:17.92 bitrate= 294.3kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/21000/24000/720x720/XZ5J0HC9IiZUEW3d.ts', offset 0, playlist 0
frame=  504 fps=171 q=-1.0 size=     752kB time=00:00:20.92 bitrate= 294.2kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/24000/27000/720x720/kcEAb91fWJTqLF_Q.ts', offset 0, playlist 0
frame=  576 fps=162 q=-1.0 size=     861kB time=00:00:23.91 bitrate= 295.0kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/27000/30000/720x720/hQ9bKqqA3fwruVLn.ts', offset 0, playlist 0
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/30000/33000/720x720/4IAJObLEwTstlKRo.ts', offset 0, playlist 0
frame=  720 fps=163 q=-1.0 size=    1217kB time=00:00:29.93 bitrate= 333.1kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/33000/36000/720x720/D0awuOXv2YNsylX5.ts', offset 0, playlist 0
frame=  792 fps=157 q=-1.0 size=    1341kB time=00:00:32.91 bitrate= 333.7kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/36000/39000/720x720/ViQbTurnYoWJUscD.ts', offset 0, playlist 0
[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/39000/42000/720x720/JXwGc5gXSMBlzTeL.ts', offset 0, playlist 0
frame=  936 fps=166 q=-1.0 size=    1586kB time=00:00:38.93 bitrate= 333.7kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/42000/45000/720x720/ndGoSMEFJpRDUJB2.ts', offset 0, playlist 0
frame= 1007 fps=159 q=-1.0 size=    1675kB time=00:00:41.92 bitrate= 327.2kbits/[hls,applehttp @ 0x82c99a0] HLS request for url 'https://video.twimg.com/amplify_video/910541641295024128/vid/45000/47798/720x720/4pWgA4P2AO7JO2X_.ts', offset 0, playlist 0
frame= 1079 fps=158 q=-1.0 size=    1765kB time=00:00:44.92 bitrate= 321.8kbits/No more output streams to write to, finishing.
frame= 1146 fps=166 q=-1.0 Lsize=    1909kB time=00:00:47.72 bitrate= 327.6kbits/s    
video:1121kB audio:750kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.003915%
Input file #0 (https://video.twimg.com/amplify_video/910541641295024128/pl/720x720/t47yOs5lhHTKUeBh.m3u8):
  Input stream #0:0 (video): 1146 packets read (1147727 bytes); 
  Input stream #0:1 (audio): 2241 packets read (784009 bytes); 
  Total: 3387 packets (1931736 bytes) demuxed
Output file #0 (file:/home/USER/.tubeup/downloads/Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.mp4.part):
  Output stream #0:0 (video): 1146 packets muxed (1147727 bytes); 
  Output stream #0:1 (audio): 2241 packets muxed (768322 bytes); 
  Total: 3387 packets (1916049 bytes) muxed
{'status': 'finished', '_total_bytes_str': '1.86MiB', 'filename': '/home/USER/.tubeup/downloads/Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.mp4', 'total_bytes': 1954445, 'downloaded_bytes': 1954445}
:: Downloaded: /home/USER/.tubeup/downloads/Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.mp4...
:: Uploading /home/USER/.tubeup/downloads/Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544...
2017-10-05 22:04:42,900 - internetarchive.item - ERROR -  error uploading Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.info.json to twitter:card-910545872206700544, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 703, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://s3.us.archive.org/twitter:card-910545872206700544/Green_Day_-_Support_%40GlblCtzn_%2B_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.info.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 9, in <module>
    load_entry_point('tubeup==0.0.11', 'console_scripts', 'tubeup')()
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 298, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 226, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 831, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 723, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading Green_Day_-_Support_@GlblCtzn_+_enter_to_go_VIP_at_one_of_our_upcoming_shows_in_South_America-910545872206700544.info.json to twitter:card-910545872206700544, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
```

Another example:

```
~$ tubeup  https://twitter.com/GreenDay/status/907260960263602177
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.5.2 - Linux-4.10.0-35-generic-i686-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[debug] Public IP address: 2601:600:9880:390:818a:d092:d4b2:18e
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[hls,applehttp @ 0x96e49a0] HLS request for url 'https://video.twimg.com/ext_tw_video/907253385765769217/pu/vid/0/3000/1280x720/z2ZgVLDqoVoz7cS-.ts', offset 0, playlist 0
[h264 @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
Input #0, hls,applehttp, from 'https://video.twimg.com/ext_tw_video/907253385765769217/pu/pl/1280x720/zWqmxJ2sVJhH3OlR.m3u8':
  Duration: 00:00:15.65, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main), 2 reference frames ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 119 kb/s
[mp4 @ 0x9e04800] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x9e04800] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:/home/USER/.tubeup/downloads/Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.mp4.part':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264, 1 reference frame ([33][0][0][0] / 0x0021), yuv420p, 1280x720 (0x0), q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 119 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[NULL @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
    Last message repeated 1 times
[hls,applehttp @ 0x96e49a0] HLS request for url 'https://video.twimg.com/ext_tw_video/907253385765769217/pu/vid/3000/6000/1280x720/67Lp6HDWDtaxl6uH.ts', offset 0, playlist 0
[NULL @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
    Last message repeated 2 times
[hls,applehttp @ 0x96e49a0] HLS request for url 'https://video.twimg.com/ext_tw_video/907253385765769217/pu/vid/6000/9000/1280x720/vqnt49Ch2qqqPXMH.ts', offset 0, playlist 0
frame=  180 fps=123 q=-1.0 size=    1024kB time=00:00:06.01 bitrate=1394.9kbits/[NULL @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
    Last message repeated 2 times
[hls,applehttp @ 0x96e49a0] HLS request for url 'https://video.twimg.com/ext_tw_video/907253385765769217/pu/vid/9000/12000/1280x720/4uditm3_EPTAJ71B.ts', offset 0, playlist 0
frame=  270 fps=125 q=-1.0 size=    1366kB time=00:00:09.00 bitrate=1243.1kbits/[NULL @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
    Last message repeated 2 times
[hls,applehttp @ 0x96e49a0] HLS request for url 'https://video.twimg.com/ext_tw_video/907253385765769217/pu/vid/12000/15649/1280x720/CxMs09-uwFOyeUAn.ts', offset 0, playlist 0
frame=  360 fps=123 q=-1.0 size=    1958kB time=00:00:12.01 bitrate=1335.7kbits/[NULL @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
    Last message repeated 1 times
frame=  410 fps=119 q=-1.0 size=    2338kB time=00:00:13.63 bitrate=1404.7kbits/[NULL @ 0x9a0d260] Current profile doesn't provide more RBSP data in PPS, skipping
    Last message repeated 1 times
No more output streams to write to, finishing.
frame=  469 fps=135 q=-1.0 Lsize=    2736kB time=00:00:15.65 bitrate=1431.6kbits/s    
video:2477kB audio:245kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.534781%
Input file #0 (https://video.twimg.com/ext_tw_video/907253385765769217/pu/pl/1280x720/zWqmxJ2sVJhH3OlR.m3u8):
  Input stream #0:0 (video): 469 packets read (2536536 bytes); 
  Input stream #0:1 (audio): 734 packets read (255722 bytes); 
  Total: 1203 packets (2792258 bytes) demuxed
Output file #0 (file:/home/USER/.tubeup/downloads/Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.mp4.part):
  Output stream #0:0 (video): 469 packets muxed (2536536 bytes); 
  Output stream #0:1 (audio): 734 packets muxed (250584 bytes); 
  Total: 1203 packets (2787120 bytes) muxed
{'_total_bytes_str': '2.67MiB', 'total_bytes': 2802025, 'downloaded_bytes': 2802025, 'status': 'finished', 'filename': '/home/USER/.tubeup/downloads/Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.mp4'}
:: Downloaded: /home/USER/.tubeup/downloads/Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.mp4...
:: Uploading /home/USER/.tubeup/downloads/Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177...
2017-10-05 22:06:46,530 - internetarchive.item - ERROR -  error uploading Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.description to twitter:card-907260960263602177, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 703, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://s3.us.archive.org/twitter:card-907260960263602177/Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.description

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 9, in <module>
    load_entry_point('tubeup==0.0.11', 'console_scripts', 'tubeup')()
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 298, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 226, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 831, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 723, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading Green_Day_-_The_stars_at_night_are_big_and_bright_thanks_Texas-907260960263602177.description to twitter:card-907260960263602177, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
```

**Comment by vxbinaca** [comment]
The cause of the problem is Tubeup names the videoID part of the item after the site-ID listed by youtube-dl, and youtube-dl lists it as `[twitter:cards]`, and the `:` is a disallowed character for Archive.org items. 

Switch `:` to `-` on our end and this one can be fixed.

**Comment by vxbinaca** [comment]
`tubeup https://twitch.tv/videos/18146455`

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15
[debug] Python version 3.4.5 - Linux-4.10.17-3-pve-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: 204.152.215.180
{'filename': '/home/vxbinaca/.tubeup/downloads/A_Fox_in_Space_Progress_Stream-v181464551.mp4', 'status': 'finished', '_elapsed_str': '14:56', 'total_bytes': 5834030664, 'elapsed': 896.0115742683411, 'downloaded_bytes': 5834030664, '_total_bytes_str': '5.43GiB'}
:: Downloaded: /home/vxbinaca/.tubeup/downloads/A_Fox_in_Space_Progress_Stream-v181464551.mp4...
:: Uploading /home/vxbinaca/.tubeup/downloads/A_Fox_in_Space_Progress_Stream-v181464551...
:: Description not saved, so not removed.
2017-10-14 21:10:53,689 - internetarchive.item - ERROR -  error uploading A_Fox_in_Space_Progress_Stream-v181464551.mp4 to twitch:vod-v181464551, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 703, in upload_file
    response.raise_for_status()
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://s3.us.archive.org/twitch:vod-v181464551/A_Fox_in_Space_Progress_Stream-v181464551.mp4
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 298, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 226, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 831, in upload
    request_kwargs=request_kwargs)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 723, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading A_Fox_in_Space_Progress_Stream-v181464551.mp4 to twitch:vod-v181464551, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
```

The symptom is this:

`twitch:vod-v181464551`

`:` is an illegal character for item identifiers and needs to be converted to `-`

**Comment by vxbinaca** [comment]
It does now just the fix isn't on Pip yet.
