### ISSUE TITLE
Access Denied - You lack sufficient privileges to write to this item

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#70]
I get this error when trying to archive a youtube video:
```
tubeup http://www.youtube.com/watch?v=KSIp5Jckg0M --use-download-archive
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.5.3 (CPython) - Linux-4.14.52-v7+-armv7l-with-debian-9.4
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
video doesn't have subtitles
 uploading Luigi_s_Mansion_-_Not-So-Spooky_Trailer_-_Nintendo_3DS-KSIp5Jckg0M.annotations.xml: [                                ] 0/ uploading Luigi_s_Mansion_-_Not-So-Spooky_Trailer_-_Nintendo_3DS-KSIp5Jckg0M.annotations.xml: [############################### ] 1/ uploading Luigi_s_Mansion_-_Not-So-Spooky_Trailer_-_Nintendo_3DS-KSIp5Jckg0M.annotations.xml: [################################] 1/1 - 00:00:00
 error uploading Luigi_s_Mansion_-_Not-So-Spooky_Trailer_-_Nintendo_3DS-KSIp5Jckg0M.annotations.xml: Access Denied - You lack sufficient privileges to write to this item.

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 722, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.us.archive.org/youtube-KSIp5Jckg0M/Luigi_s_Mansion_-_Not-So-Spooky_Trailer_-_Nintendo_3DS-KSIp5Jckg0M.annotations.xml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 359, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 328, in upload_ia
    secret_key=s3_secret_key)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 860, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 742, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading Luigi_s_Mansion_-_Not-So-Spooky_Trailer_-_Nintendo_3DS-KSIp5Jckg0M.annotations.xml to youtube-KSIp5Jckg0M, Access Denied - You lack sufficient privileges to write to this item.
```

**Comment by vxbinaca** [comment]
Is `internetarchive` configured?

**Comment by vxbinaca** [comment]
That item was darked or already ripped and you don't own privileges to it.

Closing
