### ISSUE TITLE
Tubeup error

### ISSUE THREAD

**Issue by Hiiva** [bibanon/tubeup#87]
Command ran: **tubeup https://www.youtube.com/channel/UCWVmpLlFWYD-ZMNdbw2hJzw**

Error:
```
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 356, in archive_urls
    urls, proxy, ydl_username, ydl_password, use_download_archive)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 633, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable

```

**Comment by vxbinaca** [comment]
Closed because you didn't paste the whole error.

**Comment by vxbinaca** [comment]
@Hiiva Be real with me. Is this mediocre tech channel in danger of being deleted?

**Comment by Hiiva** [comment]
That is the error I got. How can I get the whole error then?

**Comment by Hiiva** [comment]
And no, but I just wanted it archived.

**Comment by vxbinaca** [comment]
Scroll up, take the whole error and paste that in.

I doubt - in fact both of us know - you'll dump that once and never go back to it. Archive.org staff don't like you channel dumping content that's not endangered. A random foreign tech vlog channel is of least concern. Think before you dump or talk to them first. info@archive.org.

**Comment by vxbinaca** [comment]
@Hiiva your bug report should start here:

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.9 (CPython) - Linux-4.15.18-1-pve-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
```

That's where the copy and paste should start. So scroll up with your mouse wheel and edit your issue to show everything.

**Comment by Hiiva** [comment]
```
tubeup --use-download-archive https://www.youtube.com/user/OfficialDeadGaming/videos
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-141-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: This video contains content from NaxosofAmerica, who has blocked it on copyright grounds.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1978, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video contains content from NaxosofAmerica, who has blocked it on copyright grounds.


An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 356, in archive_urls
    urls, proxy, ydl_username, ydl_password, use_download_archive)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 634, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable

```

**Comment by vxbinaca** [comment]
One of the video was copyright blocked and it halted the channel rip.

**Comment by vxbinaca** [comment]
This is a youtube-dl probem not us. Looking into it a few people have complained.

Try outputting the channels videoIDs and ripping the videos one by one. the Youtube-dl FAQ tells you how to do this.
